6761050 Change product name to Sun Storage Archive Manager ---- Review Text:    * Changing product name to omit the word StorageTek, resounrce bundle product name references   * Prompt user to enable external access to Java Web Console, and add functionality in fsmgr script to do the same task. Commit Text:
Associated Bugtraq Numbers:
  6761050: Change product name to Sun Storage Archive Manager
  6602845: UI: Unable to access UI on an s11 machine

SourceCset: 268a53182dc4

diff --git a/src/samqfsui/tools/scripts/fsmgr b/src/samqfsui/tools/scripts/fsmgr
--- a/src/samqfsui/tools/scripts/fsmgr
+++ b/src/samqfsui/tools/scripts/fsmgr
@@ -1,5 +1,5 @@
 #!/bin/ksh
-
+#
 #    SAM-QFS_notice_begin
 #
 # CDDL HEADER START
@@ -26,7 +26,7 @@
 #
 #    SAM-QFS_notice_end
 #
-# ident	$Id: fsmgr,v 1.12 2008/08/06 17:38:07 ronaldso Exp $
+# ident	$Id: fsmgr,v 1.13 2008/10/22 19:48:07 ronaldso Exp $
 #
 # fsmgr:
 # It is used to set the trace level of the SAM-QFS Manager.
@@ -42,11 +42,6 @@
 # Get Solaris major revision.
 #
 RELEASE=`grep Solaris /etc/release`
-SOLREV=`echo $RELEASE | sed -e "s/^.*Sol/Sol/" | cut -f2 -d' '`
-if [ "${SOLREV}" == "" ]; then
-	echo "Could not get Solaris version from /etc/release. Exiting"
-	exit 1
-fi
 
 # for SAM-QFS Manager smcwebserver
 USR_SBIN_DIR=/usr/sbin
@@ -120,6 +115,8 @@ usage_detail_samfsui() {
 	$ECHO "\t{timeout_value_in_minutes} has to be an integer greater than"
 	$ECHO "\tor equals to 10"
 	$ECHO
+        $ECHO "connection {enable|disable}\tEnable external connection to the Java Web Console"
+        $ECHO
 
 }
 
@@ -131,8 +128,9 @@ check_su()
 	id=`/bin/id | awk -F"(" '{print $1}' | awk -F"=" '{print $2}'`
 
 	if [ "${id}" != "0" ]; then
-		EXIT_STATUS=$EXIT_CODE_NOT_SUPERUSER
-		do_exit
+            (echo "Root privilege is required to run \c"
+             echo "this installer.")
+            exit 1
 	fi
 }
 
@@ -208,6 +206,14 @@ show_current_session_timeout_value() {
 }
 
 #
+# Show current connection value
+#
+show_current_connection_value() {
+    connection=`/usr/bin/svcprop -C -p options/tcp_listen system/webconsole`
+    echo "External connections to the Java Web Console (system/webconsole:console) is set to ${connection}"
+}
+
+#
 # Change session timeout to specific value
 #
 set_timeout() {
@@ -218,8 +224,8 @@ set_timeout() {
 
     is_running=`${SMCWEBSERVER} status -p | cut -d"=" -f2`
     if [ ${is_running} = "yes" ]; then
-        $ECHO "The Web Server is currently running."
-        P="Are you sure you want to stop the Web Server in order to"
+        $ECHO "The Java Web Console is currently running."
+        P="Are you sure you want to stop the console in order to"
         P="${P} config the session timeout value?"
         REPLY=`/bin/ckyorn -Q -d "no" -p "${P}"`
 
@@ -252,6 +258,42 @@ set_timeout_value() {
     fi
 }
 
+set_connection() {
+    is_running=`${SMCWEBSERVER} status -p | cut -d"=" -f2`
+    connection=`/usr/bin/svcprop -C -p options/tcp_listen system/webconsole`
+    need_restart=0
+
+    if [ $1 = "enable" ]; then
+        if [ ${connection} = "true" ]; then
+            echo "External connections to the Java Web Console is already enabled"
+        else
+            if [ ${is_running} = "yes" ]; then
+                ${SMCWEBSERVER} stop
+            fi
+
+            /usr/sbin/svccfg -s system/webconsole setprop options/tcp_listen = \
+              true
+            need_restart=1
+        fi
+    else
+        if [ ${connection} = "false" ]; then
+            echo "External connections to the Java Web Console is already disabled"
+        else
+            if [ ${is_running} = "yes" ]; then
+                ${SMCWEBSERVER} stop
+            fi
+
+            /usr/sbin/svccfg -s system/webconsole setprop options/tcp_listen = \
+              false
+            need_restart=1
+        fi
+    fi
+
+    if [ ${need_restart} -eq 1 ]; then
+        ${SMCWEBSERVER} start
+    fi
+}
+
 # ----------------------------------
 #	MAIN PROGRAM EXECUTION
 # ----------------------------------
@@ -274,6 +316,10 @@ if [ $# -gt 0 ]; then
 		if [ $# != 1 -a $# != 2 ]; then
 			usage
 		fi
+        elif  [ "$1" = "connection" ]; then
+                if [ $# != 1 -a $# != 2 ]; then
+                        usage
+                fi
 	else 
 		usage
 	fi
@@ -282,7 +328,6 @@ else
 	# arg count = 0
 	usage
 fi
-
 
 
 case "$1" in
@@ -331,8 +376,32 @@ case "$1" in
 	esac
 			;;
 
+##################################################
+#  Enable/Disable connection to Java Web Console #
+##################################################
+'connection')
+
+        if [ $# == 1 ]; then
+                show_current_connection_value
+                $ECHO
+                exit 0
+        fi
+
+        case $2 in
+        'enable')   set_connection $2
+                    ;;
+        'disable')  set_connection $2
+                    ;;
+        *)          $ECHO "Invalid connection value entered"
+                    $ECHO
+                    usage
+                    ;;
+        esac
+        ;;
+
 *)
-	usage
-	;;
+        usage
+        ;;
+
 esac
 exit 0
diff --git a/src/samqfsui/tools/scripts/fsmgr_setup b/src/samqfsui/tools/scripts/fsmgr_setup
--- a/src/samqfsui/tools/scripts/fsmgr_setup
+++ b/src/samqfsui/tools/scripts/fsmgr_setup
@@ -26,7 +26,7 @@
 #
 #    SAM-QFS_notice_end
 #
-#  ident	$Id: fsmgr_setup,v 1.28 2008/08/06 17:38:07 ronaldso Exp $
+#  ident	$Id: fsmgr_setup,v 1.29 2008/10/22 19:48:07 ronaldso Exp $
 #
 #  This program installs/uninstalls the SUNWfsmgrr & SUNWfsmgru package
 #  along with all other necessary applications such as JATO/Lockhart/J2SE.
@@ -49,8 +49,8 @@ MINOR_REV="0"
 ZIP_FILE="fsmgr_${MAJOR_REV}.${MINOR_REV}.zip"
 LOCKHART_EXTERNAL_NAME="Sun Java(TM) Web Console"
 LH_MAJOR_VERSION=3
-LH_MINOR_VERSION=0
-LH_UPDATE_NUMBER=2
+LH_MINOR_VERSION=1
+LH_UPDATE_NUMBER=0
 LOCKHART_VERSION="${LH_MAJOR_VERSION}.${LH_MINOR_VERSION}.${LH_UPDATE_NUMBER}"
 
 BIN_DIR=/usr/sbin
@@ -463,7 +463,7 @@ unzip_files()
 	do_exit
     fi
 
-    /usr/sbin/tar xf ${LOCKHART_TARBALL}
+    # /usr/sbin/tar xf ${LOCKHART_TARBALL}
 
     if [ $? -eq 0 ]; then
 	echo "Untar ${LOCKHART_TARBALL} successfully performed!\n" >> ${MY_LOG}
@@ -826,15 +826,20 @@ install()
     # Unzip the ${ZIP_FILE} first
     unzip_files
 
-    check_install_lockhart
+    # check_install_lockhart
 
     if [ ${NEED_TO_INSTALL_LH} -eq 1 ]; then
-        # Check if Tomcat needs to be removed before LH setup kicks in
-        check_tomcat
-
-        # Kick in lockhart setup
-        install_lockhart
+        echo "OpenSolaris 2008.11 is required in this release!"
+        exit 1
     fi
+
+    # TODO: REMOVE THIS
+    #    # Check if Tomcat needs to be removed before LH setup kicks in
+    #    check_tomcat
+
+    #    # Kick in lockhart setup
+    #    install_lockhart
+    # fi
 
     # always install new GUI packages
     # update flags if the GUI packages exist
@@ -1236,7 +1241,7 @@ show_complete_install_message() {
     echo "is installed successfully.\n\n"
 
     echo "******************* PLEASE READ **********************************\n"
-    echo "Please telnet to each Sun StorEdge(TM) QFS servers to be"
+    echo "Please telnet to each Sun Storage Archive Manager (SAM) servers to be"
     echo "managed and run the following command:\n"
     echo "    /opt/SUNWsamfs/sbin/fsmadm status\n\n"
     echo "This will determine if the ${APP_NAME} daemon is running.\n"
@@ -1244,11 +1249,11 @@ show_complete_install_message() {
     echo "    /opt/SUNWsamfs/sbin/fsmadm config -a\n\n"
     echo "This command will start the ${APP_NAME} daemon that communicates with"
     echo "the ${APP_NAME}. Failure to do so will prevent ${APP_NAME}"
-    echo "from communicating with the Sun StorEdge QFS servers.\n"
+    echo "from communicating with the Sun Storage Archive Manager servers.\n"
 
     echo "Remote access to the servers used by the ${APP_NAME} is now"
     echo "restricted based on host name or IP address.  If you are managing"
-    echo "a Sun StorEdge(TM) QFS Server from a remote management station,"
+    echo "a Sun Storage Archive Manager Server from a remote management station,"
     echo "please telnet to the server and run the following command:\n"
     echo "    /opt/SUNWsamfs/sbin/fsmadm add <management_station_host_name>.<domain>"
 
@@ -1258,9 +1263,9 @@ show_complete_install_message() {
     echo "${APP_NAME} ${MAJOR_REV}.${MINOR_REV} supports the following browsers:\n"
     echo "  Browser Type                          Operating System"
     echo "  ========================================================================"
-    echo "  Netscape 7.1/Mozilla 1.7/Firefox 1.5  Solaris OS,"
-    echo "                                        MS Windows 98SE, ME, 2000, and XP"
-    echo "  Internet Explorer 6.0                 MS Windows 98SE, ME, 2000, and XP\n"
+    echo "  Netscape 7.1/Mozilla 1.7/Firefox 2.0  Solaris OS,"
+    echo "                                        MS Windows 2000, and XP"
+    echo "  Internet Explorer 6.0                 MS Windows 2000, and XP\n"
 
     echo "Now launch your web browser and type the following URL:"
     echo "     https://<hostname>.<domain>:6789\n"
@@ -1706,6 +1711,20 @@ turn_trace_on_if_needed()
     /usr/bin/rm -rf /etc/opt/SUNWsamqfsui
 }
 
+prompt_enable_connection()
+{ 
+    connection=`/usr/bin/svcprop -C -p options/tcp_listen system/webconsole`
+    if [ "z${connection}" = "zfalse" ]; then
+        msg1="External connections to the Java Web Console are currently disabled.  This will stop your browser from communicating to the Java Web Console and SAM-QFS Manager will not work properly.\n\nDo you want to enable external connections?"
+        ans=`/bin/ckyorn -Q -d "yes" -W 60 -p "${msg1}?"`
+
+        if [ "${ans}" = "y" -o "${ans}" = "yes" -o "${ans}" = "Y" -o \
+             "${ans}" = "YES" ]; then
+            /opt/SUNWfsmgr/bin/fsmgr connection enable
+        fi
+    fi
+}
+
 #
 # The method writes a dummy file to create a hook for the SUNWfsmgr packages
 # to check if the user is pkgadding the packages without running the
@@ -1741,7 +1760,7 @@ case $# in
 
         create_users
         fix_users_account_if_needed
-
+        prompt_enable_connection
         show_configuration_files
         show_complete_install_message
         turn_trace_on_if_needed
